place  = input("Enter a place: ")
person = input("Enter a person: ")
pastTenseVerb = input("Enter a past tense verb: ")
noun = input("Enter a noun: ")
adjective = input("Enter an adjective: ")
pluralNoun = input("Enter a plural noun: ")
food = input("Enter a food: ")
noun2 = input("Enter another noun: ")
emotion = input("Enter an adjective/emotion: ")
pastTenseVerb2 = input("Enter another past tense verb: ")
adjective2 = input("Enter another adjective: ")

print("A year ago I went to", place)
print("I went with", person, "and we", pastTenseVerb)
print("Me and", person, "talked about", noun)
print("We saw some very", adjective, pluralNoun)
print("Me and", person, "ate some", food)
print("At the", place, "we noticed a", noun2)
print("Because of this", person, "was", emotion)
print ("I complyed and", pastTenseVerb2, "I felt very", adjective2)
print("The end")
